name: Diagnostic Test

on:
  push:
    branches: [ main ]

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: List Repository Files
      run: |
        pwd
        ls -la
        cat provider.tf backend.tf main.tf variable.tf || echo "One or more files not found"

    - name: Print Environment Variables
      run: |
        echo "ARM_CLIENT_ID=$ARM_CLIENT_ID"
        echo "ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID"
        echo "ARM_TENANT_ID=$ARM_TENANT_ID"
        echo "ARM_ACCESS_KEY=$ARM_ACCESS_KEY"